# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "975ab589ddc019e57a6c852d2de26031"
name = "PUMPSHOT"
application_url = "https://pumpshot.shopify.scipnet.org"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/order_created"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_all_orders"

[auth]
redirect_urls = [ "https://pumpshot.shopify.scipnet.org/api/auth" ]
